In [9]:
import numpy as np                           #importing numpy

In [10]:
a=[1,2,3]                                    #list
type(a)

list

In [11]:
np.array(a)                                  #converting list into array

array([1, 2, 3])

In [15]:
n=np.array([[1,2,3], [5,6,7]])               #array creation     

In [16]:
type(n)                                      

numpy.ndarray

In [21]:
n[0][0]                                   #data accessing

1

In [24]:
n.shape

(2, 3)

In [25]:
np.array([1,2,3,4],ndmin=2)                      #selecting no. of dimension (ndmin=20)

array([[1, 2, 3, 4]])

In [26]:
np.array([1,2,3,4],ndmin=20)      

array([[[[[[[[[[[[[[[[[[[[1, 2, 3, 4]]]]]]]]]]]]]]]]]]]])

In [27]:
np.array([1,2,3,4],dtype=complex)                     #converting data into the complex form

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [29]:
np.array([(1,2,3),(4,5,6)])             #converting tuple into array

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
d=np.array([(2,8),(4,9)],dtype=[('a','<i2'),('b','<i4')])                   #to change data type 

In [38]:
type(d[0][0])                                                    #checking datd type (int16)=8*2

numpy.int16

In [37]:
type(d[0][1])

numpy.int32

In [42]:
#matrix data type
    
m=np.mat([1,2,2,3])           #to create matrix data type
m

matrix([[1, 2, 2, 3]])

In [46]:
q=np.array(m)                            #converting matrix into array

In [44]:
np.asanyarray(m)                            #try to get an array value of matrix

matrix([[1, 2, 2, 3]])

In [47]:
np.asanyarray(q)

array([[1, 2, 2, 3]])

In [48]:
q

array([[1, 2, 2, 3]])

In [49]:
#deep copy and swallow copy

a=np.array([1,2,3,8])

In [50]:
b=a                                 #swapping operation                          #known as 'swallow Copy'

In [51]:
b

array([1, 2, 3, 8])

In [52]:
b[0]=56                             #assigned value for variable 'b'

In [53]:
b

array([56,  2,  3,  8])

In [54]:
a                                          #but changes also reflect in variable 'a'

array([56,  2,  3,  8])

In [55]:
c=np.copy(a)                               #create copy of variable 'a'          #known as 'Deep Copy'

In [56]:
c

array([56,  2,  3,  8])

In [57]:
a[0]=656                                   #assigned value for 'a'

In [58]:
a

array([656,   2,   3,   8])

In [59]:
c                                         #but it doesn't reflect in variable 'c'

array([56,  2,  3,  8])

In [60]:
#creating array using function

np.fromfunction(lambda x,y: x==y,(3,4))                             #checking condition 'x==y'

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [62]:
np.fromfunction(lambda x,y: x+y,(3,4))                           #(3,4) is shape of array

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.]])

In [63]:
np.fromfunction(lambda x,y: x*y,(3,4))   

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [67]:
#creating array from string

np.fromstring('4,5,6', dtype=int, sep=",")

array([4, 5, 6])

In [69]:
np.fromstring('a,re,gg', dtype=str, sep=",")

ValueError: zero-valued itemsize

In [80]:
l=np.array([[1,2,3],[3,4,4],[6,7,8]])

In [81]:
l

array([[1, 2, 3],
       [3, 4, 4],
       [6, 7, 8]])

In [82]:
l.ndim                               #checking dimension of array

2

In [83]:
l.size                           #no. of element

9

In [85]:
l.shape                          #shape of array

(3, 3)

In [89]:
m=np.arange(1.,9.98,.65)                           #same as 'range function', to generate data ,also float data 

In [91]:
list(m)                      #converting into list

[1.0,
 1.65,
 2.3,
 2.9499999999999997,
 3.5999999999999996,
 4.25,
 4.8999999999999995,
 5.549999999999999,
 6.199999999999999,
 6.85,
 7.499999999999999,
 8.149999999999999,
 8.799999999999999,
 9.45]

In [95]:
#linespcae : to create no. data within given range

l=np.linspace(3,7,19)              #'3,7' is given range & '19' no. of dividation of range

In [96]:
l

array([3.        , 3.22222222, 3.44444444, 3.66666667, 3.88888889,
       4.11111111, 4.33333333, 4.55555556, 4.77777778, 5.        ,
       5.22222222, 5.44444444, 5.66666667, 5.88888889, 6.11111111,
       6.33333333, 6.55555556, 6.77777778, 7.        ])

In [107]:
p=np.linspace(3,7,5,endpoint= False)                           #'endpoints'to get value with upper bound value

In [108]:
p

array([3. , 3.8, 4.6, 5.4, 6.2])

In [109]:
p=np.linspace(3,7,8,endpoint= False, retstep=True)             #to get diffrence between two value

In [110]:
p

(array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5]), 0.5)

In [115]:
p=np.linspace(3,7, axis=0)   

In [114]:
p

array([3.        , 3.08163265, 3.16326531, 3.24489796, 3.32653061,
       3.40816327, 3.48979592, 3.57142857, 3.65306122, 3.73469388,
       3.81632653, 3.89795918, 3.97959184, 4.06122449, 4.14285714,
       4.2244898 , 4.30612245, 4.3877551 , 4.46938776, 4.55102041,
       4.63265306, 4.71428571, 4.79591837, 4.87755102, 4.95918367,
       5.04081633, 5.12244898, 5.20408163, 5.28571429, 5.36734694,
       5.44897959, 5.53061224, 5.6122449 , 5.69387755, 5.7755102 ,
       5.85714286, 5.93877551, 6.02040816, 6.10204082, 6.18367347,
       6.26530612, 6.34693878, 6.42857143, 6.51020408, 6.59183673,
       6.67346939, 6.75510204, 6.83673469, 6.91836735, 7.        ])

In [121]:
np.zeros((2,3,5))         #filled with zeros as per shape &'3,5' is shape of table and '2' no. of array to be created

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [122]:
np.zeros((7,3,5)) 

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [124]:
np.ones((2,3,4))                           #same as 'zeros', to fill '1' value

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [126]:
np.ones((2,3,4))+1                            #can be performed mathematical solution

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [142]:
np.logspace(3.7,4.6,6)       #similar to 'linspace', but here gives logarithmic value between range with no. of instence

array([ 5011.87233627,  7585.77575029, 11481.53621497, 17378.00828749,
       26302.67991895, 39810.71705535])

In [143]:
 np.logspace(3.7,4.6,6, base=1.34)           #changing log value with base value

array([2.95316528, 3.11291038, 3.28129655, 3.4587912 , 3.64588704,
       3.84310343])

In [132]:
np.random.rand(2,9)

array([[0.07603418, 0.14591907, 0.48193646, 0.25352924, 0.40451969,
        0.52530546, 0.31498125, 0.79538661, 0.47570582],
       [0.51680283, 0.75737506, 0.59122606, 0.19782656, 0.59027345,
        0.33048992, 0.29897021, 0.25921716, 0.2191636 ]])

In [138]:
np.empty((2,5))                              #create zero data

array([[6.65838300e-312, 2.37151510e-322, 0.00000000e+000,
        0.00000000e+000, 9.76118064e-313],
       [1.16095484e-028, 7.52736939e+252, 2.09603058e-110,
        2.91237123e+257, 4.71294503e+257]])

In [141]:
np.eye((4))                                      #squared array , place '1' diagonally

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [144]:
i=np.random.rand(3,4)

In [145]:
i

array([[0.28902159, 0.9522123 , 0.42335204, 0.44593829],
       [0.29158012, 0.90797936, 0.5873221 , 0.49294035],
       [0.06899698, 0.25984873, 0.85076008, 0.91958948]])

In [146]:
i.reshape(12,1)                      #reshaping operation 

array([[0.28902159],
       [0.9522123 ],
       [0.42335204],
       [0.44593829],
       [0.29158012],
       [0.90797936],
       [0.5873221 ],
       [0.49294035],
       [0.06899698],
       [0.25984873],
       [0.85076008],
       [0.91958948]])

In [158]:
u=np.random.randint(2,7,(5,6))                       #gives integer values between given range, with define shape

In [159]:
u

array([[4, 6, 2, 6, 6, 3],
       [3, 6, 2, 3, 5, 5],
       [5, 4, 2, 2, 6, 2],
       [2, 6, 6, 2, 5, 4],
       [6, 5, 4, 5, 5, 2]])

In [160]:
u[2:4,0:3]                                #fetching data w.r.t index

array([[5, 4, 2],
       [2, 6, 6]])

In [161]:
u>4                             #checking condtion

array([[False,  True, False,  True,  True, False],
       [False,  True, False, False,  True,  True],
       [ True, False, False, False,  True, False],
       [False,  True,  True, False,  True, False],
       [ True,  True, False,  True,  True, False]])

In [162]:
u[u>4]                                  #checking condtion & getting data

array([6, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 6, 5, 5, 5])

In [163]:
u[0][3]='89'                                 #assigning value to specific index

In [164]:
u

array([[ 4,  6,  2, 89,  6,  3],
       [ 3,  6,  2,  3,  5,  5],
       [ 5,  4,  2,  2,  6,  2],
       [ 2,  6,  6,  2,  5,  4],
       [ 6,  5,  4,  5,  5,  2]])

In [168]:
b=np.array([[2,4,6],[3,5,7]])

In [169]:
b

array([[2, 4, 6],
       [3, 5, 7]])

In [170]:
c=np.array([[4,6,8],[5,7,9]])

In [171]:
c

array([[4, 6, 8],
       [5, 7, 9]])

In [172]:
b+c                                      #addition operation wrt index

array([[ 6, 10, 14],
       [ 8, 12, 16]])

In [173]:
b-c                                 #Subtraction operation wrt index

array([[-2, -2, -2],
       [-2, -2, -2]])

In [174]:
b*c                             #NOTE:-  #Multiplication operation wrt index

array([[ 8, 24, 48],
       [15, 35, 63]])

In [175]:
b/c                                       #dividation operation wrt index

array([[0.5       , 0.66666667, 0.75      ],
       [0.6       , 0.71428571, 0.77777778]])

In [180]:
m1=np.array([[1,2],[3,4]])

In [181]:
m1

array([[1, 2],
       [3, 4]])

In [182]:
m2=np.array([[4,5],[7,8]])

In [183]:
m2

array([[4, 5],
       [7, 8]])

In [184]:
m1@m2                                 #This is MATRIX MULTIPLICATION

array([[18, 21],
       [40, 47]])

In [185]:
m1**2                                   #Power of m1

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [186]:
pow(m1,2)                              #Power of m1

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [197]:
n3=np.zeros([3,4])

In [198]:
n3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [199]:
n3+2                               #indexwise broadcasting operation

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [200]:
m3=np.array([[1,2,3,4]])      

In [201]:
m3

array([[1, 2, 3, 4]])

In [202]:
n3+m3                                   #Row wise broadcasting operation

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [203]:
n4=np.array([[9,7,5]])

In [204]:
n4

array([[9, 7, 5]])

In [205]:
n3+n4

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [206]:
n4=np.array([[9,7,5]]).T                          #transpose operation for convertion between row to column or vice versa

In [207]:
n4

array([[9],
       [7],
       [5]])

In [214]:
n5=n3+n4                                       #Column wise braodcasting operation

In [215]:
n5

array([[9., 9., 9., 9.],
       [7., 7., 7., 7.],
       [5., 5., 5., 5.]])

In [220]:
j1=np.sqrt(n5)                                      #to get square root                                  

In [221]:
j1

array([[3.        , 3.        , 3.        , 3.        ],
       [2.64575131, 2.64575131, 2.64575131, 2.64575131],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [217]:
np.exp(n5)                                      #to get exponential value

array([[8103.08392758, 8103.08392758, 8103.08392758, 8103.08392758],
       [1096.63315843, 1096.63315843, 1096.63315843, 1096.63315843],
       [ 148.4131591 ,  148.4131591 ,  148.4131591 ,  148.4131591 ]])

In [218]:
np.log10(n5)                                    #to get logarithmic 10 value

array([[0.95424251, 0.95424251, 0.95424251, 0.95424251],
       [0.84509804, 0.84509804, 0.84509804, 0.84509804],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [222]:
np.fmod(n5,j1)                             #to get remainder value

array([[0.        , 0.        , 0.        , 0.        ],
       [1.70849738, 1.70849738, 1.70849738, 1.70849738],
       [0.52786405, 0.52786405, 0.52786405, 0.52786405]])